name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest # Usaremos a versão mais recente do Ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install system dependencies and Python 3.11
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool python3.11-dev libffi-dev

      - name: Set up Python with the new version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer
          # Instala as dependencias do seu app aqui, se houver mais alguma
          pip install https://github.com/kivymd/KivyMD/archive/master.zip

      - name: Build with Buildozer
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
